# Generated by Django 3.1.5 on 2021-10-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textappl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippettbl',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textappl.tagtbl'),
        ),
    ]
